apps/funcionarios/urls.py
from .views import ( 
    FuncionariosList, 
    FuncionarioEdit, 
    FuncionarioDelete, 
    FuncionarioCreate,
    relatorio_funcionarios,
    RelatorioFuncionariosHtml
)
from django.urls import path

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioCreate.as_view(), name='create_funcionario'),
    path('editar/<int:pk>', FuncionarioEdit.as_view(), name='edit_funcionario'),
    path('deletar/<int:pk>', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('relatorio-funcionarios', relatorio_funcionarios, name='relatorio_funcionarios'),
    path('relatorio-funcionarios-html', RelatorioFuncionariosHtml.as_view(), name='relatorio_funcionarios_html')
]

gestao_rh/urls.py
from django.contrib import admin
from rest_framework import routers
# from django.conf.urls.i18n import i18n_patterns
from apps.core import views
from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import RegistroHoraExtraViewSet
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/banco-horas', RegistroHoraExtraViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(router.urls)),
    path('api-auth/', include(
        'rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    dono = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def __str__(self):
        return self.descricao
    
    def get_absolute_url(self):
        return reverse('edit_funcionario', kwargs={'pk': self.dono.id})

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa
from django.db.models import Sum
from django.urls import reverse


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    usuario = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(
        Empresa, on_delete=models.PROTECT, null=True, blank=True
    )
    de_ferias = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

    @property
    def total_horas_extra(self):
        total = self.registrohoraextra_set.filter(
            utilizada=False
        ).aggregate(
            Sum('horas'))['horas__sum']
        return total or 0

    def get_absolute_url(self):
        return reverse("list_funcionarios")

apps/registro_hora_extra/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('edit_funcionario', kwargs={"pk": self.funcionario.id})

    def __str__(self):
        return self.motivo

apps/funcionarios/api/views.py
from rest_framework import viewsets
from .serializers import FuncionarioSerializer
from apps.funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication


class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer
    authentication_classes = (TokenAuthentication, )
    permission_classes = (IsAuthenticated, )

apps/funcionarios/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView,
    CreateView,
    View
)
from .models import Funcionario
from django.contrib.auth.models import User
import io
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        queryset = Funcionario.objects.filter(empresa=empresa_logada)
        return queryset


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.usuario = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)


def relatorio_funcionarios(request):
    response = HttpResponse(content='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(250, 810, "Relatório de funcionários")
    funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)

    str_ = "Nome: %s | Hora Extra: %2.f"
    y = 790
    for funcionario in funcionarios:
        p.drawString(10, y, str_ % (funcionario.nome, funcionario.total_horas_extra ))
        y -= 20

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response


class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode('UTF-8')), response
        )
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf'
            )
            response['Content-Disposition'] = 'attachment; filenmae=%s.pdf' % filename
            return response
        else:
            return HttpResponse('Error Rendering PDF', status=400)
        

class RelatorioFuncionariosHtml(View):
    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',
            'request': request
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
    <form method="POST">
        {% csrf_token %}
        <h1>Voce esta certo que quer deletar {{ obj }}</h1>
        {{ form }}
        <button type='submit'>Confirmar</button>
    </form>
{% endblock main %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
    <form method="POST">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type='submit' class="btn btn-success mt-2">Salvar</button>
    </form>

    <h2>Documentos</h2>
    <ul>
        {% for documento in object.documento_set.all %}
            <li><a href="{{ documento.arquivo.url }}">{{ documento }}</a></li>
        {% endfor %}
    </ul>
    {% if object %}
        <a href="{% url 'create_documento' object.id %}" class="btn btn-info mt-2">Adicionar documento</a>
    {% endif %}

    <h2>Banco de horas</h2>
    <ul>
        {% for registro_hora in object.registrohoraextra_set.all %}
            <li><a href="{% url 'edit_hora_extra' registro_hora.id %}">{{ registro_hora.motivo }} | {{ registro_hora.horas }}</a></li>
        {% empty %}
            Nenhuma hora cadastrada
        {% endfor %}
    </ul>

    {% if object %}
        <h3>Total de horas extras: {{ object.total_horas_extra }}</h3>
    {% endif %}
{% endblock main %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
    {% for funcionario in object_list %}
        <a href="{% url 'edit_funcionario' funcionario.id %}">{{ funcionario }}</a>
        <a href="{% url 'delete_funcionario' funcionario.id %}">Deletar</a>
        <br>
    {% endfor %}
    
    <a href="{% url 'create_funcionario' %}" class="btn btn-success">Novo</a>
    <a href="{% url 'relatorio_funcionarios' %}" class="btn btn-info">Relatório de funcionários</a>
    <a href="{% url 'relatorio_funcionarios_html' %}" class="btn btn-info">Relatório de funcionários HTML</a>
{% endblock main %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}

{% block styles %}
    <style>
        h1 {
            color: red;
        }
    </style>
{% endblock styles %}

{% block main %}
    <h1>Meu relatorio</h1>
    <h2>{{ sales }}</h2>
{% endblock main %}